{% set version = "2.3.4" %}

package:
  name: m2w64-muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: 0c3fa54a3ebf36dda0ed3e7cd5451c964afbb15102bdbcba08aafb359a290121

build:
  number: 1
  skip: true  # [not win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\include\\muParser.h exit 1
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\lib\\libmuparser.dll.a exit 1
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\bin\\libmuparser.dll exit 1

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: LICENSE
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
    - mingwandroid
