{% set version = "2.3.2" %}

package:
  name: m2w64-muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: b35fc84e3667d432e3414c8667d5764dfa450ed24a99eeef7ee3f6647d44f301

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\include\\muParser.h exit 1
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\lib\\libmuparser.dll.a exit 1
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\bin\\libmuparser.dll exit 1

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
    - mingwandroid
