{% set version = "2.2.6.1" %}

package:
  name: m2w64-muparser
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/beltoforion/muparser/archive/v{{ version }}.tar.gz
  sha256: d2562853d972b6ddb07af47ce8a1cdeeb8bb3fa9e8da308746de391db67897b3
  patches:
    - no-console.patch
    - revert-PR46.patch

build:
  number: 2
  skip: true  # [not win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\include\\muParser.h exit 1
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\lib\\libmuparser.dll.a exit 1
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\bin\\libmuparser.dll exit 1

about:
  home: http://muparser.beltoforion.de/
  license: MIT
  license_file: License.txt
  summary: A fast math parser library

extra:
  recipe-maintainers:
    - jschueller
    - mingwandroid
