travis:
  secure:
    BINSTAR_TOKEN: ErUixLMHr7MDZvgby97z8Q43fgCr1xR+5HUFaQevuBY+KX6OtdwVlWHMvd9j6nARKml1NuCzynpGJ0th6RKM0e0Nual+3t9Z3fQhy1iW0+whCFqX0F3MYUci7k60l2MasMhEx8UZxV0bMMGBmeO9Z0Ly54j7XKwb4quVA1Lq+1tigBJz7Y1X1lWM8nPt7QbAT/ErBMO0fsiuaQ6h7BptFupHWUrqCJoCtOm6NFER/a4Cd/mZamKq3iAWGlliuZpIuilwmaDfAnxsa9AGC3mfYF97i3N0nvrK1RYx03ajaUqPNZRS3K+ExVP8ATQQ5y8aOW4WLxrRxZYwcEh1VqIV0EEFd9dU/hGfEh5t6Tj+NdzatR+5R5c54at/UrR+mcxG/ZcqhgG9PsIn8BJ23hZM8LWH1+Hn/+ejgGsvWTi4s4NFd29l0qnA//wxdzAA3hkQOYwReszjsPTHG0EV6bmvU1NDg3tS5mcUNH2P/O1vfIGJvLNeDsxgDKNkJ3quy5MI7JTnpRiY4V0Hloh9wLaCxivgjMBK8+XbeLddynV2nftUWNBvQf2BB3p91aLjSgg9ryU0ftjNmslSSNT0VA9hS8idDzg/Iz7vb0nwC60pNFJFtyQPuvoPjyyoQg7vh/JJMZQ6w0TPS2QRrokM62WoMsHJoPvxzL43xIzPtaLpE6s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
