travis:
  secure:
    BINSTAR_TOKEN: e+asxANIsIDKsuAdbOhlbZgbV2E1XzMLlJmpv5Tsd8dOTxmv+YyvbMq3oqkDC0bpqYQ2ok0k4iONV68zbEKbOgY5aaDa8pL38LJbGmB2mgRj0qQgCa+EHsKyO7EPKmYTs5+Qfh04C6Ad3+7hgajRalhYgxJVnkO1/F2HN3w59pj1bMJ1ZofSl+izM2SRyPQf9bhbYluJEvVxadnlHXWy+hjrluDqsAZ0MILXUiJLulzDcasxpxWRjSVQwGe1S4gSb5M1sAt+/m6sb+xZgUV9olDaxTPC1/Pmp0eLMos004g7ovZnDaMydWg+AmYI/gb56pvW8EPF/Hn3wKHKzorbvbLbM7+kH5ElKwIARVI1e6dYZLqYP+p4SPQ5DQ6184679QbSabf/h758Bno/6/zJugiFTP2zyZmdk0smEAvDdaBhwGtuLx/KQVpcCBV5J8qKhaXrMeNW9QHVYvNr1KGHVL28ib7A5Xu1NWrBpYUItUEiOVDUvAlNKhWeild+B4CahOcZpx9JTX4tql6H3qJbz3i/UyfDHiKxpGiWfulrmhV+pavsDmsaDaYIBZM2qp76f5pSDjh/DT3QK2mHSO8kS2Lhjb1YLtufX6S/K7thzd/oVo5N74HLG+d7Uflh6mLf+gz054zR+acN3xOCNhGjXUVhtd7ydDsl/fGsrizfXEI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
