travis:
  secure:
    BINSTAR_TOKEN: ZqqnG7Up0ktiWbD4TUnIXYHunNSqeBwTeWtBJmNFEZiK91bcACS2HB0ibDC/TkHXT55t2qkfMw1+TYi+6HgR+hYmXDvZ9+kIfH02RskZ9ikV/PPrGPXA5MPpOOGvW9kIcyptPVQaDjfXde49y8y7ZTh+H9F+ULEmIzp3aFIWO3p7KOrzZ9IMHKjSwXHbFEAUmWT84yVMiEz3PKZIgZ9MWuO8xtVttNuFT1ngk4AL8ADivMEPu/ygQoh7CJ+aseK4IcOZcqYQpO6eKTNXNjdNiO2sukfU2SiGncJwxVBzFu06yO6YnQoKrFoPjvr+92UG0tLDaYza8oYlefi7FOgN3fzx/RcgT6H5JcCSg+T0YBboJonOJLTK3Yh7IIHSs+o4EpzfvMzbjSOFNT7ffVV7+H6Dej6M+/+ciUe+GUpvl/BNJlSAMIVY3SXhZh/eRATeR4MlWVhPlpuH3h/sn3MYeoP/b+i7hs+xLGhqV3ZbkUJyaSHik7VRQDsrfirnErwSUqM4tHbV+McnRZ8FzrXkOQ5SiDCIu7HRlg7rN0zUwlO5dMvwyUr/2qxbbBqq20Iw3U1Chc/9lrcfJcPqQ7lL6hcrstk7OorFsm2ZJR0+DfzccrQSvXbznv8EeTe1w9+ocoi43y2tB1IMd0w9KpsFghqbA8kH+fbLzjLdSNaUogw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
